/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ui;

import Model.KaryModel;
import Controller.KaryFormController;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.text.DecimalFormat;

/**
 *
 * @author LENOVO
 */


public class KaryForm extends javax.swing.JFrame {

    /**
     * Creates new form KaryForm
     */
    KaryFormController controller;
    String gambar = "";
    byte[] tampilan;
    
    public KaryForm() {
        initComponents();
        this.setTitle("Rumah Makan barokah - Tambah data karyawan");
        setIconImage(new ImageIcon(getClass().getResource("/gambar/Logo.png")).getImage());
        controller = new KaryFormController(this);
        judulLbl.setText("Tambah data karyawan");
        gambarLbl.setText("Tidak ada foto");
        ubahBtn.setEnabled(false);
    }
    
    public KaryForm(String kode){
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/gambar/Logo.png")).getImage());
        this.setTitle("Rumah Makan barokah - Ubah data karyawan");
        controller = new KaryFormController(this,kode);
        judulLbl.setText("Ubah data karyawan");
        tambahBtn.setEnabled(false);
        idTxt.setEnabled(false);
        KaryModel model1 = controller.tampil(kode);
        tampilan = model1.getFoto();
        if(tampilan == null){
            gambarLbl.setText("Tidak ada foto");
        }else{
            ImageIcon image = new ImageIcon(new ImageIcon(model1.getFoto()).getImage().getScaledInstance(gambarLbl.getWidth(), gambarLbl.getHeight(), Image.SCALE_SMOOTH)); 
            gambarLbl.setIcon(image);
        }
        cekBtn.setEnabled(false);
        cancelBtn.setEnabled(false);
    }

    public JTextArea getAlamatTxtArea() {
        return alamatTxtArea;
    }

    public void setAlamatTxtArea(JTextArea alamatTxtArea) {
        this.alamatTxtArea = alamatTxtArea;
    }

    public JComboBox<String> getCboJabatan() {
        return cboJabatan;
    }

    public void setCboJabatan(JComboBox<String> cboJabatan) {
        this.cboJabatan = cboJabatan;
    }

    public JLabel getGambarLbl() {
        return gambarLbl;
    }

    public void setGambarLbl(JLabel gambarLbl) {
        this.gambarLbl = gambarLbl;
    }

    public JTextField getNamaTxt() {
        return namaTxt;
    }

    public void setNamaTxt(JTextField namaTxt) {
        this.namaTxt = namaTxt;
    }

    public JLabel getUkuranLbl() {
        return ukuranLbl;
    }

    public void setUkuranLbl(JLabel ukuranLbl) {
        this.ukuranLbl = ukuranLbl;
    }

    public JTextField getIdTxt() {
        return idTxt;
    }

    public void setIdTxt(JTextField idTxt) {
        this.idTxt = idTxt;
    }

    public String getGambar() {
        return gambar;
    }

    public void setGambar(String gambar) {
        this.gambar = gambar;
    }

    public byte[] getTampilan() {
        return tampilan;
    }

    public void setTampilan(byte[] tampilan) {
        this.tampilan = tampilan;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judulLbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        gambarLbl = new javax.swing.JLabel();
        tambahFoto = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ukuranLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        namaTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cboJabatan = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatTxtArea = new javax.swing.JTextArea();
        tambahBtn = new javax.swing.JButton();
        ubahBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        kembaliBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        cekBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(455, 575));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judulLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        judulLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulLbl.setText("Tambah/Ubah data karyawan");
        getContentPane().add(judulLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 438, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Foto Karyawan"));

        gambarLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        tambahFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/folder.png"))); // NOI18N
        tambahFoto.setText("Masukkan Foto");
        tambahFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahFotoActionPerformed(evt);
            }
        });

        jLabel5.setText("Format file foto : jpg, png");

        jLabel6.setText("Maks. file foto : 2 Mb");

        jLabel7.setText("Syarat file foto :");

        jLabel8.setText("Ukuran file foto :");

        ukuranLbl.setText("Masukkan foto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gambarLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ukuranLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                    .addComponent(tambahFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(gambarLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tambahFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(ukuranLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(19, 19, 19))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 460, 210));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Karyawan"));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nama karyawan :");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Jabatan :");

        cboJabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Alamat :");

        alamatTxtArea.setColumns(20);
        alamatTxtArea.setRows(5);
        jScrollPane1.setViewportView(alamatTxtArea);

        tambahBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/plus.png"))); // NOI18N
        tambahBtn.setText("Tambah");
        tambahBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBtnActionPerformed(evt);
            }
        });

        ubahBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pencil_edit.png"))); // NOI18N
        ubahBtn.setText("Ubah");
        ubahBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahBtnActionPerformed(evt);
            }
        });

        cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/close_delete.png"))); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        kembaliBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/small back.png"))); // NOI18N
        kembaliBtn.setText("Kembali");
        kembaliBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cboJabatan, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(namaTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
                        .addGap(0, 31, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tambahBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ubahBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kembaliBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboJabatan, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ubahBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kembaliBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 460, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Id. Karyawan :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, 30));
        getContentPane().add(idTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 270, 30));

        cekBtn.setText("Cek");
        cekBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekBtnActionPerformed(evt);
            }
        });
        getContentPane().add(cekBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 70, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tambahFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahFotoActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
         fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
         FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg","png");
         

         fileChooser.addChoosableFileFilter(filter);
         int result = fileChooser.showSaveDialog(null);
         if(result == JFileChooser.APPROVE_OPTION){
             File selectedFile = fileChooser.getSelectedFile();
             String path = selectedFile.getAbsolutePath();
             Path paths = Paths.get(path);
            try {
                long bytes = Files.size(paths);
                DecimalFormat formatData = new DecimalFormat("#.##");
                double a;
                a = Double.valueOf(formatData.format((float)bytes/1000000));
                if(a > 2.048){
                    JOptionPane.showMessageDialog(rootPane, "Ukuran file gambar terlalu besar."+"\nUkuran file = "+(a)+" Mb");
                }else{
                    gambarLbl.setIcon(ubahukuran(path));
                    
                    setGambar(path);
                    ukuranLbl.setText(String.valueOf(a)+" Mb");
                }
            } catch (IOException ex) {
                Logger.getLogger(MenuForm.class.getName()).log(Level.SEVERE, null, ex);
            }
             
              }
         else if(result == JFileChooser.CANCEL_OPTION){
             System.out.println("No Data");
         }
    }//GEN-LAST:event_tambahFotoActionPerformed

    private void cekBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekBtnActionPerformed
        if(!this.getIdTxt().getText().trim().isEmpty()){
            controller.cek();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Mohon diisi terlebih dahulu sebelum dicek");
        }
    }//GEN-LAST:event_cekBtnActionPerformed

    private void tambahBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBtnActionPerformed
    if(!this.getIdTxt().getText().trim().isEmpty()&
            !this.getNamaTxt().getText().trim().isEmpty() & 
            !this.getAlamatTxtArea().getText().trim().isEmpty()){    
        try {
            controller.insert();
        } catch (IOException ex) {
            Logger.getLogger(MenuForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }else{
        JOptionPane.showMessageDialog(rootPane, "Mohon diisi semuanya");
    }
    }//GEN-LAST:event_tambahBtnActionPerformed

    private void ubahBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahBtnActionPerformed
    if(!this.getIdTxt().getText().trim().isEmpty()&
            !this.getNamaTxt().getText().trim().isEmpty() & 
            !this.getAlamatTxtArea().getText().trim().isEmpty()){
        try {
            controller.update();
        } catch (IOException ex) {
            Logger.getLogger(KaryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }else{
        JOptionPane.showMessageDialog(rootPane, "Mohon diisi semuanya");
    }
    }//GEN-LAST:event_ubahBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        controller.cancel();
        gambarLbl.setIcon(null);
        gambarLbl.setText("Tidak ada foto");
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void kembaliBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_kembaliBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KaryForm().setVisible(true);
            }
        });
    }
    
    public ImageIcon ubahukuran(String gambar){
        ImageIcon MyImage = new ImageIcon(gambar);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(gambarLbl.getWidth(), gambarLbl.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamatTxtArea;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JComboBox<String> cboJabatan;
    private javax.swing.JButton cekBtn;
    private javax.swing.JLabel gambarLbl;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judulLbl;
    private javax.swing.JButton kembaliBtn;
    private javax.swing.JTextField namaTxt;
    private javax.swing.JButton tambahBtn;
    private javax.swing.JButton tambahFoto;
    private javax.swing.JButton ubahBtn;
    private javax.swing.JLabel ukuranLbl;
    // End of variables declaration//GEN-END:variables
}
