/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ui;

import Controller.PembayaranController;
import java.io.*;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author LENOVO
 */
public class Pembayaran extends javax.swing.JFrame {

    /**
     * Creates new form Pembayaran
     */
    PembayaranController controller;
    String kode;
    public Pembayaran(String kode) {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/gambar/Logo.png")).getImage());
        this.setTitle("Rumah Makan Barokah - Pembayaran");
        controller = new PembayaranController(this);
        controller.viewAll(kode);
        setKode(kode);
        totalHarga.setText(controller.totalharga());
        noPesanan.setText(kode);
    }

    public JTable getPembayaranTabel() {
        return pembayaranTabel;
    }

    public JLabel getNoPesanan() {
        return noPesanan;
    }

    public JLabel getTotalHarga() {
        return totalHarga;
    }

    public String getKode() {
        return kode;
    }

    public void setKode(String kode) {
        this.kode = kode;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pembayaranTabel = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        noPesanan = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        totalHarga = new javax.swing.JLabel();
        bayarBtn = new javax.swing.JButton();
        kembaliBtn = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pembayaran");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, 30));

        pembayaranTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Nama Menu", "Jumlah", "Harga", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(pembayaranTabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 480, 230));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("No. Pesanan:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 120, 30));

        noPesanan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(noPesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 170, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Total Harga : Rp.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        totalHarga.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        totalHarga.setText("total");
        getContentPane().add(totalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 315, -1, -1));

        bayarBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bayarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/calculator.png"))); // NOI18N
        bayarBtn.setText("Bayar");
        bayarBtn.setAlignmentY(5.0F);
        bayarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(bayarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 120, 40));

        kembaliBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kembaliBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/small back.png"))); // NOI18N
        kembaliBtn.setText("Kembali");
        kembaliBtn.setMaximumSize(new java.awt.Dimension(71, 25));
        kembaliBtn.setMinimumSize(new java.awt.Dimension(71, 25));
        kembaliBtn.setPreferredSize(new java.awt.Dimension(71, 25));
        kembaliBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliBtnActionPerformed(evt);
            }
        });
        getContentPane().add(kembaliBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 120, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bayarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarBtnActionPerformed
        // TODO add your handling code here:
        String kode = this.noPesanan.getText();
        double totalharga = Double.parseDouble(controller.totalharga());
        String p = JOptionPane.showInputDialog("Masukkan uang pembayaran");
//        JOptionPane.showMessageDialog(rootPane, Integer.parseInt(p));
        Double uang = Double.parseDouble(p);
        if(uang<totalharga){
            JOptionPane.showMessageDialog(rootPane, "Uang Kurang, silahkan bayar kembali");
        }else{
            controller.bayar(kode, totalharga);
            new Nota(kode,uang).show();
            dispose();
        }
    }//GEN-LAST:event_bayarBtnActionPerformed

    private void kembaliBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_kembaliBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String kode = "";
                new Pembayaran(kode).setVisible(true);
            }
        });
    }
    
    public void cetak(String kode){
        JasperReport reports;
      Koneksi k = new Koneksi(); 
//      String path=".\\src\\Laporan\\notaPembayaran.jasper";
      try {
//          reports = (JasperReport) JRLoader.loadObjectFromFile(path);
//          JasperPrint jprint = JasperFillManager.fillReport(reports, null, k.getKoneksi());
////          JasperViewer jviewer = new JasperViewer(jprint, false);
////          jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
////          jviewer.setVisible(true);
////          System.out.println("Masuk try");
            File namafile = new File("/Laporan/notaPembayaran.jasper");
            JasperPrint jp = JasperFillManager.fillReport(namafile.getPath(), null, k.getKoneksi());
            JasperViewer.viewReport(jp);
      } catch (Exception ex) {
          JOptionPane.showMessageDialog(rootPane, ex);
      }      

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bayarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kembaliBtn;
    private javax.swing.JLabel noPesanan;
    private javax.swing.JTable pembayaranTabel;
    private javax.swing.JLabel totalHarga;
    // End of variables declaration//GEN-END:variables
}
