/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ui;

import Controller.PesananController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.*;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author LENOVO
 */
public class Pesanan extends javax.swing.JFrame {

    /**
     * Creates new form pesanan
     */
    PesananController controller;
    int batas = 5, awal = 0, jumlah;
    String teks;
    
    public Pesanan() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/gambar/Logo.png")).getImage());
        this.setTitle("Rumah Makan barokah - Pembayaran Pesanan");
        controller = new PesananController (this);
        String tglsekarang;
        SimpleDateFormat format = new SimpleDateFormat("E, YYYY-MM-dd");
        tglsekarang = format.format(new Date());
        tanggal.setText(tglsekarang);
        setJam();
        totalLbl.setText(String.valueOf(jumlah));
        pagetxt.setEditable(false);
        pagetxt.setText(teks);
        kondisiAwal();
        if(jumlah>batas){
            selBtn.setEnabled(true);
        }else{
            selBtn.setEnabled(false);
        }
        pesananBtn.setEnabled(false);
    }
    
    public final void setJam() {
        ActionListener taskPerformer;
        taskPerformer = new ActionListener() {
            
            @Override
            public void actionPerformed(ActionEvent evt) {
                String nol_jam = "", nol_menit = "", nol_detik = "";

                java.util.Date dateTime = new java.util.Date();
                int nilai_jam = dateTime.getHours();
                int nilai_menit = dateTime.getMinutes();
                int nilai_detik = dateTime.getSeconds();

                if (nilai_jam <= 9) {
                    nol_jam = "0";
                }
                if (nilai_menit <= 9) {
                    nol_menit = "0";
                }
                if (nilai_detik <= 9) {
                    nol_detik = "0";
                }

                String jam1 = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);

                jam.setText(jam1 + ":" + menit + ":" + detik + "");
            }
        };
        new Timer(1000, taskPerformer).start();
    }
    
    public void kondisiAwal(){
        setAwal(0);
        sblBtn.setEnabled(false);
    }

    public JTable getPesantbl() {
        return pesantbl;
    }

    public int getBatas() {
        return batas;
    }

    public void setBatas(int batas) {
        this.batas = batas;
    }

    public int getAwal() {
        return awal;
    }

    public void setAwal(int awal) {
        this.awal = awal;
    }

    public int getJumlah() {
        return jumlah;
    }

    public void setJumlah(int jumlah) {
        this.jumlah = jumlah;
    }

    public String getTeks() {
        return teks;
    }

    public void setTeks(String teks) {
        this.teks = teks;
    }

    public JTextField getCariTxt() {
        return cariTxt;
    }

    public void setCariTxt(JTextField cariTxt) {
        this.cariTxt = cariTxt;
    }
    
    public void refresh()
    {
        kondisiAwal();
        getCariTxt().setText("");
        controller.viewTabel();
        if(jumlah>batas){
            selBtn.setEnabled(true);
        }else{
            selBtn.setEnabled(false);
        }
    }    
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jam = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        keluarbtn = new javax.swing.JButton();
        menuBtn = new javax.swing.JButton();
        pesananBtn = new javax.swing.JButton();
        tentangBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pesantbl = new javax.swing.JTable();
        bayarBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        selBtn = new javax.swing.JButton();
        sblBtn = new javax.swing.JButton();
        pagetxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        totalLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cariTxt = new javax.swing.JTextField();
        cariBtn = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PESANAN");

        jam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jam.setForeground(new java.awt.Color(255, 255, 255));
        jam.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jam.setText("Jam");
        jam.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jam.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jamComponentShown(evt);
            }
        });

        tanggal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tanggal.setForeground(new java.awt.Color(255, 255, 255));
        tanggal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tanggal.setText("Tanggal");
        tanggal.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tanggalComponentShown(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jam, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jam)
                            .addComponent(tanggal))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 659, -1));

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));

        keluarbtn.setText("Keluar");
        keluarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarbtnActionPerformed(evt);
            }
        });

        menuBtn.setText("Menu");
        menuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBtnActionPerformed(evt);
            }
        });

        pesananBtn.setText("Pesanan");
        pesananBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesananBtnActionPerformed(evt);
            }
        });

        tentangBtn.setText("Tentang");
        tentangBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tentangBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(menuBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
            .addComponent(pesananBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(keluarbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(tentangBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(menuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pesananBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tentangBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(keluarbtn)
                .addGap(16, 16, 16))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 66, -1, -1));

        pesantbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No. Pesanan", "Nama Pemesan", "Tanggal Pemasanan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(pesantbl);
        pesantbl.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, 312));

        bayarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/calculator.png"))); // NOI18N
        bayarBtn.setText("Bayar");
        bayarBtn.setAlignmentY(3.0F);
        bayarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(bayarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 107, 40));

        refreshBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/refresh.png"))); // NOI18N
        refreshBtn.setText("Refresh");
        refreshBtn.setAlignmentY(3.0F);
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });
        getContentPane().add(refreshBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 110, 40));

        selBtn.setText(">>");
        selBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selBtnActionPerformed(evt);
            }
        });
        getContentPane().add(selBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 425, 50, 30));

        sblBtn.setText("<<");
        sblBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sblBtnActionPerformed(evt);
            }
        });
        getContentPane().add(sblBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 425, 50, 30));

        pagetxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(pagetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 425, 70, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Cari Pesanan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        totalLbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        totalLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalLbl.setText("12");
        getContentPane().add(totalLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Pesanan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, -1, -1));
        getContentPane().add(cariTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 150, 30));

        cariBtn.setText("Cari");
        cariBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariBtnActionPerformed(evt);
            }
        });
        getContentPane().add(cariBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, 30));

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        setSize(new java.awt.Dimension(673, 549));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void keluarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarbtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login().show();
    }//GEN-LAST:event_keluarbtnActionPerformed

    private void bayarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarBtnActionPerformed
        try{
        int row = this.getPesantbl().getSelectedRow();
        String kode = this.getPesantbl().getValueAt(row, 0).toString();
        new Pembayaran(kode).show();
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Pilih dahulu pesanan yang mau dibayar");
        }
    }//GEN-LAST:event_bayarBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        refresh();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void pesananBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesananBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Kamu sudah berada di pesanan");
    }//GEN-LAST:event_pesananBtnActionPerformed

    private void menuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Home().show();
    }//GEN-LAST:event_menuBtnActionPerformed

    private void sblBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sblBtnActionPerformed
        // TODO add your handling code here:
        if(awal>0){
            setAwal(awal-batas);
            if(!this.getCariTxt().getText().trim().isEmpty()){
                controller.searchTabel();
                pagetxt.setText(teks);
            }else{
                controller.viewTabel();
                pagetxt.setText(teks);
            }
            if(awal-batas<0){
                sblBtn.setEnabled(false);
            }
            selBtn.setEnabled(true);
        }else{
            sblBtn.setEnabled(false);
        }
    }//GEN-LAST:event_sblBtnActionPerformed

    private void selBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selBtnActionPerformed
        // TODO add your handling code here:
        if(awal+batas<getJumlah()){
            setAwal(awal+batas);
            if(!this.getCariTxt().getText().trim().isEmpty()){
                controller.searchTabel();
                pagetxt.setText(teks);
            }else{
                controller.viewTabel();
                pagetxt.setText(teks);
            }
            if(awal+batas<getJumlah()){
                selBtn.setEnabled(true);
            }else{
                selBtn.setEnabled(false);
            }
        }else{
            selBtn.setEnabled(false);
        }
        sblBtn.setEnabled(true);
    }//GEN-LAST:event_selBtnActionPerformed

    private void cariBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariBtnActionPerformed
        // TODO add your handling code here:
        if(!this.getCariTxt().getText().trim().isEmpty()){
            kondisiAwal();
            controller.searchTabel();
            if(jumlah>batas){
                selBtn.setEnabled(true);
            }else{
                selBtn.setEnabled(false);
            }
            pagetxt.setText(teks);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Masukkan inputan sebelum mencari");
        }
    }//GEN-LAST:event_cariBtnActionPerformed

    private void tentangBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tentangBtnActionPerformed
        // TODO add your handling code here:
        new Tentang().show();
    }//GEN-LAST:event_tentangBtnActionPerformed

    private void tanggalComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tanggalComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalComponentShown

    private void jamComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jamComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jamComponentShown

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
//        new Nota().show();
        String p = JOptionPane.showInputDialog("Masukkan uang pembayaran");
        JOptionPane.showMessageDialog(rootPane, Integer.parseInt(p));
    }//GEN-LAST:event_btnPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pesanan().setVisible(true);
            }
        });
    }
    
    public void cetak(){
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bayarBtn;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton cariBtn;
    private javax.swing.JTextField cariTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jam;
    private javax.swing.JButton keluarbtn;
    private javax.swing.JButton menuBtn;
    private javax.swing.JTextField pagetxt;
    private javax.swing.JButton pesananBtn;
    private javax.swing.JTable pesantbl;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton sblBtn;
    private javax.swing.JButton selBtn;
    private javax.swing.JLabel tanggal;
    private javax.swing.JButton tentangBtn;
    private javax.swing.JLabel totalLbl;
    // End of variables declaration//GEN-END:variables
}
